### ISSUE TITLE
Should use atomic PSETEX instead of SET+EXPIRE/PEXPIRE

### ISSUE THREAD

**Issue by clue** [WyriHaximus/reactphp-cache-redis#17]
This project should probably use the atomic [`PSETEX`](https://redis.io/commands/psetex) command instead of two individual `SET` and `EXPIRE` calls:

```
PSETEX key 1500 value
```
```
SET key value
PEXPIRE key 1500
```

Additionally, in fact this project currently uses `EXPIRE` instead of `PEXPIRE` and as such only provides full second accuracy. It's my understanding this should probably be updated to use millisecond precision as given above.

**Comment by WyriHaximus** [comment]
It should indeed! Thank you for bringing this to my attention, would you be up for creating a PR changing the behavior?

**Comment by clue** [comment]
I've spotted this during a quick project evaluation for a project I'm currently working on, so this will be of interest in the future. Expect this to take at least a couple of weeks, so let's see who's faster with filing a PR, cheers! :1st_place_medal:

**Comment by WyriHaximus** [comment]
#18 is up with a fix for this :+1:

**Comment by clue** [comment]
@WyriHaximus Thanks for the quick update, LGTM! :shipit:

**Comment by WyriHaximus** [comment]
@clue FYI: https://github.com/WyriHaximus/reactphp-cache-redis/releases/tag/3.0.1
