### ISSUE TITLE
PHP 8 support?

### ISSUE THREAD

**Issue by pavarnos** [WyriHaximus/reactphp-cache-redis#25]
Hi. Thanks for the PHP 8 support in WyriHaximus/reactphp-http-middleware-session. Is it possible to upgrade your toolchain for react-cache-(fallback|json|redis) ? thank you!

**Comment by WyriHaximus** [comment]
Yes, will do it somewhere this week 👍

**Comment by WyriHaximus** [comment]
There you go: https://github.com/WyriHaximus/reactphp-cache-redis/releases/tag/4.2.0

**Comment by pavarnos** [comment]
legend! thanks!
