### ISSUE TITLE
Promise v3 support?

### ISSUE THREAD

**Issue by SQKo** [WyriHaximus/reactphp-cache-redis#59]
Is there any plan to support react/promise v3 with this library?

**Comment by WyriHaximus** [comment]
Unlocking it for usage, or full type templates and all moving to only v3?

**Comment by WyriHaximus** [comment]
v4.4.0 has unlock promise v3, v4.5.0 will be only promise v3: https://github.com/WyriHaximus/reactphp-cache-redis/releases/tag/4.4.0

**Comment by WyriHaximus** [comment]
In short 4.5.0 is current waiting for https://github.com/clue/reactphp-redis/pull/145 and https://github.com/clue/reactphp-redis/pull/134 to be released. I've reached out through: https://github.com/clue/reactphp-redis/issues/148

**Comment by WyriHaximus** [comment]
Just released https://github.com/WyriHaximus/reactphp-cache-redis/releases/tag/4.5.0 now that https://github.com/clue/reactphp-redis/issues/148 has been resolved through https://github.com/clue/reactphp-redis/pull/152
